import Categories from "@/components/home/Categories";
import Hero from "@/components/home/Hero";
import Navbar from "@/components/shared/navbar/Navbar";
import Head from "next/head";
import { useContext, useEffect } from "react";
import { GET_CATEGORIES, GET_PRODUCTS } from "@/graphql/queries";
import { client } from '@/graphql';
import DataContext from "@/global/context/DataContext";
import { fetchData } from "@/utils/fetchData";

export default function Home({ categoriesData, productsData }) {
  const { setContextData, products } = useContext(DataContext);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setContextData({ categories: categoriesData, products: productsData });
      } catch (error) {
        console.error('Error fetching and setting data:', error);
      }
    };

    fetchData();
  }, []);

  console.log("omg", products);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <Hero />
        <Categories />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { categoriesData, productsData } = await fetchData();
  return {
    props: {
      categoriesData,
      productsData,
    },
    revalidate: 604800,
  };
}